import type { NextPage } from "next";
import Head from "next/head";
import Card from "../libs/ui/Card";
import Layout from "../libs/ui/Layout";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const postQuery = trpc.useQuery(["post.getAllPosts"]);

  if (postQuery.isLoading) {
    return <p>Loading...</p>;
  }

  return (
    <Layout>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto max-w-5xl">
        <div className="grid justify-center grid-cols-1 gap-5">
          {postQuery.data?.map((post) => (
            <Card key={post.id} to={`/post/${post.id}`}>
              <div className="p-5">
                <Card.Title>{post.title}</Card.Title>
                <Card.Description>{post.content}</Card.Description>
                <Card.ReadMoreButton />
              </div>
            </Card>
          ))}
        </div>
      </div>
    </Layout>
  );
};

export default Home;
